pymysql/connections.py
=> Don't wrap MySQLError with MySQLError.

pymysql/cursors.py, pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_dbapi20.py, runtests.py
As defined in DB-API 2.0.
Fixes #284
=> Return empty tuple instead when no rows in result

pymysql/connections.py
=> Add max_allowed_packet option (default: 16MB)

pymysql/connections.py, setup.cfg
=> connection: Refactoring

pymysql/cursors.py, pymysql/tests/test_issues.py
=> Fix TypeError while show_warnings

pymysql/connections.py
=> Enable no_delay by default and deprecate it

.travis.yml
new feature of travis from travis-ci/travis-build/pull/303
=> Travis build against MariaDB too version 5.5, 10.0 and 10.1

.coveragerc, .gitignore, .travis.yml, README.rst, pymysql/connections.py, tox.ini
instructions:
- log into https://coveralls.io using github auth and enable the PyMySQL/PyMySQL repository
- merge pull request
output example https://coveralls.io/github/grooverdan/PyMySQL
=> Add Coveralls.io code coverage measurements

pymysql/tests/test_connection.py
Adding some tests to cover the rest of the connection module
might add some more.
=> add test test_no_delay_warning

pymysql/connections.py
=> prepare for when mysql might want to move beyond version 5

.travis.yml, pymysql/connections.py, pymysql/tests/test_connection.py
=> Raise ProgrammingError when previous multi result not fetched.

pymysql/connections.py, pymysql/tests/test_connection.py
=> Calling connection's method during multiple result breaks command sync

pymysql/connections.py
=> Fix auth fail on MySQL 5.1

pymysql/connections.py
=> Fix misuse of `max_allowed_packet`

pymysql/connections.py
=> Don't ignore port in config

pymysql/cursors.py, pymysql/tests/test_cursor.py, runtests.py
=> Support %% in executemany

pymysql/connections.py
Since mysql-5.6.2 (commit id: 6deae781c4c8e7018a31d56bc050f99e2411cbc0),
mysql may reply with incomplete row to "SHOW SLAVE HOSTS" commands.
This happens if slave_uuid does not exists, this happens if the slave
does not issue this command:
set @slave_uuid='UUID'
See:
https://github.com/mysql/mysql-server/commit/6deae781c4c8e7018a31d56bc050f99e2411cbc0#diff-a06ba9f19ff21c6cdb9bcfb44cc185cfR708
=> connections: Fixup parsing of incomplete rows

pymysql/converters.py
=> Fix convertion error on Py3 and use_unicode=False

pymysql/connections.py, pymysql/converters.py
=> Allow custom encoding mapping via conv parameter.

pymysql/connections.py
=> Add read_timeout and write_timeout options.

pymysql/tests/test_cursor.py
This adds the missing closing bracket.
=> Fix syntax error in test_cursor.

pymysql/converters.py, pymysql/tests/test_basic.py
=> Fix loading json data

pymysql/charset.py, pymysql/connections.py, pymysql/converters.py, pymysql/tests/test_basic.py
=> Fix SELECT CAST(... AS JSON) cause UnicodeError

pymysql/charset.py
and other collations from id=244 through id=247
=> add support for utf8mb4_unicode_520_ci

README.rst
Reference correct PEP and make it a hyperlink
=> Fix PEP reference in README

pymysql/__init__.py
without resorting to venvs or sys.path altering
we use this over at web2py/web2py ^_^
=> makes the module portable 

pymysql/connections.py
Use same default value
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_connect_timeout
=> Change default connect_timeout to 10.

pymysql/connections.py
=> Raise SERVER_LOST error for MariaDB's shutdown packet

.github/ISSUE_TEMPLATE.md
=> Small grammar changes to ISSUE_TEMPLATE.md

pymysql/connections.py
=> fix KeyError when server reports unknown collation

docs/source/user/development.rst
I decided to run the tests and found that the instructions are out-of-date.
=> Update the testing setup instructions

pymysql/connections.py, pymysql/converters.py, pymysql/tests/test_issues.py, pymysql/tests/thirdparty/test_MySQLdb/capabilities.py, pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_capabilities.py
=> _binary prefix is now optional

pymysql/connections.py, pymysql/cursors.py, pymysql/tests/test_nextset.py
=> Clear cursor attributes before calling nextset()

pymysql/tests/test_issues.py
couple of warnings/errors resulting from deprecated functions as per commit messages.
=> fix test issue363 for MySQL-8.0

pymysql/connections.py
=> add docs for read_timeout/write_timeout

.travis.yml, .travis/initializedb.sh, pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_capabilities.py
=> Travis docker mysql 8.0

.travis.yml
=> travis: Run auth test with Python 2.7

pymysql/_auth.py
=> Fix caching_sha2_password didn't work with PY2

pymysql/_auth.py
=> Disable debug logging in _auth

pymysql/_auth.py
-Import byte2int and int2byte as well as io
=> Maintain compatibility with Python 3 and old MySQL Password.

pymysql/connections.py
=> doc: connections - remove unsupport capath/cipher

pymysql/connections.py
=> sys.argv is not always available

pymysql/connections.py
=> Support non-ascii program_name on Python 2

pymysql/connections.py
=> Remove auto program_name from sys.argv

pymysql/_auth.py
=> Warn when old password is used

pymysql/connections.py, pymysql/tests/test_connection.py
=> Deprecate context manager interface of Connection

pymysql/connections.py
Optimized packet reading speed 26 times faster on my pc
=> Optimize packet reading

pymysql/connections.py
Fixing some typos as I read the code.
=> Fix minor typos in comments

pymysql/converters.py, pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_capabilities.py
=> use better format for float

.travis.yml, setup.py, tox.ini
Python 3.8 is official now, test this package against this new version
=> Add Python 3.8 support

pymysql/err.py
=> Use OperationalError for unknown error with code>1000.

pymysql/converters.py
=> Fix decimal literal.

pymysql/connections.py
Fix inconsistency between connection read/write timeout error messages and actual value checks.
=> Fix connection timeout error messages

pymysql/cursors.py
=> Fix simple typo: suports -> supports

pymysql/_auth.py, pymysql/converters.py
Remove unnecessary imports. I used [LGTM](https://lgtm.com/projects/g/PyMySQL/PyMySQL/?mode=list&id=py%2Funused-import) and verified manually that the imports were actually not used.
=> Remove unused imports

pymysql/converters.py
=> Add missing import

.travis/initializedb.sh, pymysql/_auth.py, tests/test_auth.py
=> Fix sha256 and caching_sha2 auth

pymysql/connections.py
=> Add context manager to Connection.

.github/workflows/test.yaml
=> Actions: Run auth tests

docs/source/user/examples.rst, pymysql/connections.py
=> Remove warning for db and passwd.

pymysql/cursors.py, pymysql/tests/test_basic.py
=> Removed _last_executed because of duplication with _executed

pymysql/converters.py
The docstrings contained non-existent function names.
=> Fix docstring for converter functions

pymysql/connections.py, pymysql/cursors.py
- dot at the end of descriptions
- 3rd instead of 2nd person
- more type information
- minor rephrasing
=> Improve docstrings

pymysql/connections.py
=> Fix calling undefined function

pymysql/connections.py
=> Stop showing handler name when hander is not set.

README.rst
it would also be nice to have information on coverage directly in PRs, e.g. via [PR comments](https://docs.coveralls.io/coveralls-notifications#pull-request-comments)
=> Fix coveralls branch in README.rst

.github/workflows/test.yaml, ci/docker.json
Maps the mysqld.sock file from the container. MariaDB just worked while MySQL exits and needs the permissions fixed.
Closes  #1023
=> Add unix socket connection test

.github/workflows/test.yaml
=> Upgrade more GitHub Actions

.github/workflows/test.yaml, README.md
=> Bump mariadb version

.github/workflows/test.yaml
=> ci: use codecov@v3

pymysql/connections.py, pymysql/tests/test_connection.py
Added support for SSL private key password in Connection class to handle encrypted keys.
=> Added ssl_key_password param

pymysql/connections.py, pymysql/err.py, pymysql/tests/test_err.py, pyproject.toml
=> Support error packet without sqlstate

pymysql/connections.py, pymysql/tests/test_connection.py
=> make sure to also close `connection._rfile` in `Connection._force_close`

README.md
Appreciate the feedback! I've removed the try-except changes and updated the repo description to include MariaDB. Addresses issue (#1180)
=> Added MariaDB in readme description (#1180)
