pymysql/cursors.py
pymysql/tests/test_basic.py

Instead of falling back to executing each statement separately when "on duplicate update" is there, it builds a batch call.

fix issue 288: executemany now works with "insert ... on duplicate update" 

---

pymysql/connections.py
pymysql/converters.py

I've based this on benchmark from Mike Bayer's mini-benchmark from his [evaluation of PyMySQL] (https://wiki.openstack.org/wiki/PyMySQL_evaluation). It showed that the most time-consuming parts of protocol parsing code are:
* converting rows from protocol representation to Python objects;
* lots of `read()` calls;
* huge amount of method calls overall.
This branch summarizes fixes that optimize all of these aspects. Generally speedup is gained by:
* moving work that can be done before row parsing loop to the top of it;
* avoiding copying buffers around (almost all but most general read() calls are eliminated, bytes object concatenation is avoided);
* reducing amount of calls to `struct.unpack` methods my squashing consecutive calls into one (and replacing them with `struct.unpack_from` to …

Protocol parsing optimizations

---

CHANGELOG
pymysql/_compat.py
pymysql/connections.py
pymysql/cursors.py
pymysql/tests/base.py
pymysql/tests/test_DictCursor.py
pymysql/tests/test_cursor.py

This PR adds tests to confirm that things are cleaned up if a Cursor or SSCursor is discarded in the middle of results.   The cleanup routine of MySQLResult handles this already.   A warning is added to Connection if an unbuffered result was left open, and a subsequent execute call is made.
With this patch, the issue of slow program termination reported in #287 is resolved.  
What I am not explicitly testing, but I *think* is OK, is if the statement had multiple result sets.  It looks like the way MySQLResult._finish_unbuffered_query works should handle this as well, but let me know if that's not the case.

Remove __del__ from Cursor; warn on unconsumed SSCursor results

---

pymysql/connections.py
pymysql/tests/test_connection.py

Given that the CLIENT.MULTI_STATEMENTS flag is set, it is valid for the init_command supplied by the connection contain multiple statements.  Since on one ok_packet is read this causes subsequent queries to return unexpected results since client/server are out of sync.
Demonstrated by:
```
def test_init_command(self):
conn = pymysql.connect(
init_command='SELECT "baz"; SELECT "boz"',
**self.databases[0]
)
c = conn.cursor()
c.execute('select "foobar";')
self.assertEqual(('foobar',), c.fetchone())
conn.close()
```

Multi-statement init_command causes subsequent query to fail

---

pymysql/connections.py
pymysql/converters.py
pymysql/tests/test_connection.py

MySQLdb provides a second argument to connection's escape method where an 'encoders' dict can be supplied.
For compatibility with existing code could this be added to PyMySQL?
From MySQLdb, _mysql.c:
```
static char _mysql_escape__doc__[] =
"escape(obj, dict) -- escape any special characters in object obj\n\
using mapping dict to provide quoting functions for each type.\n\
Returns a SQL literal string.";
```
Proposed test case:
```
def test_escape_custom_object(self):
con = self.connections[0]
cur = con.cursor()
class Foo(object):
value = "bar"
encoder = lambda x: x.value
self.assertEqual(con.escape(Foo(), encoders={Foo: encoder}), "bar")
```

Support custom mapping for connection's escape method

---

pymysql/connections.py

If bytes get passed in they are escaped using escape_bytes with a `surrogateescape` but then are not encoded properly here without this change.  This seems to fix the issue for me.

Need to use surrogate escape here too I think

---

README.rst

I think this change is important, as it might prevent some problems users could run into.

Set the 'charset' in the example for starting a connection

---

pymysql/cursors.py

There is some need to have a method that returns the exact string that is passed to the DB in SQL cursors. Some of the discussions include:
* http://stackoverflow.com/questions/3748295/getting-the-sql-from-a-django-queryset
* http://stackoverflow.com/questions/1074212/show-the-sql-django-is-running
* http://stackoverflow.com/questions/5266430/how-to-see-the-real-sql-query-in-python-cursor-execute
Django does not have such feature. [Ticket 17741](https://code.djangoproject.com/ticket/17741) tried to address this, but was not able since this is adapter-dependent:
> Django never actually interpolates the parameters: it sends the query and the parameters separately to the database adapter, which performs the appropriate operations [aaugustin (core developer)]
People have been using the …

Add mogrify to Cursor, which returns the exact string to be executed

---

pymysql/connections.py

otherwise and exception is thrown on when connecting to unix_socket
([Errno 95] Operation not supported).
created databases and set connection file as follows. 
<pre>
cat pymysql/tests/databases.json
[
{"host": "localhost", "unix_socket": "/tmp/s.sock", "user": "root", "passwd": "", "db": "test_pymysql",  "use_unicode": true, "local_infile": true},
{"host": "localhost", "unix_socket": "/tmp/s.sock", "user": "root", "passwd": "", "db": "test_pymysql2" }
]
Then ran tox
<pre>
======================================================================
ERROR: test_utf8mb4 (pymysql.tests.test_connection.TestConnection)
This test requires MySQL >= 5.5
----------------------------------------------------------------------
File …

only set no_delay on TCP sockets

---

pymysql/connections.py

Adds defer_connect (default False) arguement to connection constructor.
Move _connect method to public connect and add sock parameter.
The goal of this is to allow a mysql connection over an existing socket like object.
I'm a backer of the https://www.kickstarter.com/projects/1839007321/mysql-cli project that will provide an alternate mysql client. One of the feature requests is to run a mycli locally and get it to connect to the server over ssh. I was looking into https://github.com/paramiko/paramiko/blob/master/paramiko/channel.py for this. This Channel class presents all the same interfaces as a socket and passing this to PyMySQL will allow a direct connection to the remote server over ssh without an intermediate proxy locally.

Allow socket like options to be used

---

README.rst

`pymysql.connect` function now use `password` as keyword argument instead of `passwd`.

Fix spelling in README example

---

pymysql/cursors.py
pymysql/tests/test_issues.py

This should fix both #321 and #364.
I've incorporated the changes from #364 and hopefully addressed the review feedback. Since both of these issues touched the same code paths, one of them would have to be rebased on top of the other one.
Basically this pulls out the special PY2 handling out of the execute/mogrify function and also applies it to the executemany function. This all feels like a bit of a hack, but I don't know enough about the code to figure out how to better fix this. Pointers welcome :)

Address encoding issues with mixed str/bytes in executemany and with iterables.

---

pymysql/connections.py
pymysql/tests/test_issues.py

I mixed up the issue number while working on 364, so corrected that test inside this PR.
Otherwise this replicates the example given in #363 and extends it to test for WKT/WKB values. Interestingly enough selecting for both WKT and WKB values worked before this change. It's just selecting for the internal MySQL binary geometry format that failed.
@danieljwest does this test and fix look good to you?

Classify Geometry as a text type, refs #363.

---

README.rst

oops. Changed to repo, missed the branch.

Fix url for coveralls badge - wrong branch

---

.coveragerc
.travis.databases.json
.travis.initialize.db.sh
.travis.yml
pymysql/connections.py
pymysql/tests/test_SSCursor.py
pymysql/tests/test_connection.py
pymysql/tests/test_issues.py

MySQL-5.7 has some warnings in a couple of cases so the test cases have been modified.
Geom functions give warnings now was ST_{function} is the newer syntax so just accept the warnings for now.
#364 I'm not sure if silencing those warnings is correct.
For other tests I've worked around the constraints of 5.7 by altering the test in a compatible way to 5.0+ and haven't interfered with the objective of the test.

Add MySQL-5.6 and 5.7 to test suite

---

pymysql/connections.py

This pull merges a lot of SSL fixes:
* Allow TLSv1.1 or higher connections whilst not allowing SSLv2 and SSLv3 by default
* Allow passing custom SSLContexts in the ssl parameter
* Support for the cipher and capath parameter
* Allow enabling or disabling checking of the hostname

TLS/SSL Fixes

---

pymysql/__init__.py

This will allow Django to use DateTimeField with microseconds.
It checks the driver version here:
https://github.com/django/django/blob/master/django/db/backends/mysql/features.py#L53

Bump version_info

---

pymysql/converters.py
pymysql/cursors.py

Faster bytes escaping on Python 3

---

pymysql/__init__.py
pymysql/converters.py
pymysql/tests/test_issues.py

On Python 2, bytearray represents binary data.
On Python 3, bytes and bytearray represents binary data.
reference:
https://github.com/go-sql-driver/mysql/pull/382
https://dev.mysql.com/doc/relnotes/mysql/5.5/en/news-5-5-46.html
https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-27.html

Add _binary prefix for binaries.

---

pymysql/_compat.py
pymysql/converters.py
pymysql/tests/__init__.py
pymysql/tests/test_converters.py

Fix escape_string doesn't accept unicode on Python 2

---

pymysql/converters.py

PyMySQL should follow MySQLdb behavior.
fixes #324, #435.

Fix escaping unknown Python objects

---

pymysql/connections.py

This matches the renaming done in 93297cc5af45542d302fe11ef968621427ea60fd.
Without this there are sometimes errors during Python process shutdown and garbage collection inside the `__del__` method. The `__del__` starts with:
```
def __del__(self):
if self._sock:
```
This sometimes throws an AttributeError for `self._sock`. I think what happens here, is that the instance level dict is cleared before the `__del__` method is invoked, so `_sock` isn't there anymore. The class level attribute ensures that there is a fallback, even with the instance `__dict__` already cleared out.

Rename connection class level socket attribute to _sock.

---

pymysql/connections.py

KeyError occurs when there's no entry in OS user database for a current user. This is quite often the case for Docker containers.
Example traceback:
```
File "/tmp/unpacked-eggs/pymysql.egg/pymysql/__init__.py", line 90, in <module>
from pymysql import connections as _orig_conn
File "/tmp/unpacked-eggs/pymysql.egg/pymysql/connections.py", line 34, in <module>
DEFAULT_USER = getpass.getuser()
File "/usr/lib/python2.7/getpass.py", line 158, in getuser
return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 33333'
```

Catch KeyError from getpass.getuser()

---

pymysql/connections.py
pymysql/tests/test_load_local.py

There isn't a compelling reason for using an SSCursor for such a command
(as it is really intented for queries that return large result sets),
but I use some wrapper code that always uses these types of cursors
(since most interactions are heavy SELECTs), so prefer it to work
in all cases. Added a test to demonstrate.

Fixing LOAD DATA LOCAL INFILE for SSCursor* types

---

pymysql/converters.py
pymysql/tests/test_converters.py

Due to the limitations of IEEE754, we may lost precision when
converting string back to datetime objects, for example:
`float('0.511581') * 1e6`, gives us `0.511580`, which is unexpected.
In order to address that issue, use of `float` is avoided.

Avoid IEEE754 converting fraction of seconds

---

pymysql/cursors.py
pymysql/tests/test_DictCursor.py
pymysql/tests/test_issues.py

Dear PyMySQL team,
Here are a couple of suggestions (similar to what I submitted to [MySQLdb#101](https://github.com/PyMySQL/mysqlclient-python/pull/101) regarding warning handling in your library:
1. _Include error code in warnings, not just string_  
I thought it would make sense for the `Warning` instances to not just have a string argument but, same as with errors, to also include the error code (as first argument, with string being second).
2. Fix warning propagation for unbuffered queries  
Since warning count is not available until whole result has been fetched, handle warnings "_deferred_" (simiarly to MySQldb)

Warning propagation improvements

---

pymysql/err.py
pymysql/tests/__init__.py
pymysql/tests/test_err.py

Pull request for issue #507.
Revert the changes made in commit 02910b7 to the mysql error packet
parsing, as it didn't take the CLIENT_PROTOCOL_41 case into account. 
It appears that the non-CLIENT_PROTOCOL_41 case was off by one as well
(sliced data on 4 vs 3).
I also added two new tests to cover those cases.
See: https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html

Revert error packet parsing changes

---

pymysql/connections.py

When connecting via TCP/IP, provide a means to the client to bind the
socket to be created to a specific source address.  This is useful
when the client host has multiple network interfaces and a specific
one must be used for database traffic.
Add a new optional "bind" argument to class Connection, to specify the
interface from which to connect to the DB. Argument can be a hostname
or an IP address.

Allow connecting to the DB from a specific network interface

---

pymysql/connections.py

I was change my project using torndb from Python2 to Python3.5, and i found that when i use PyMySQL instead of MySQLdb, error was raised when client tried to connect to mysql.
```
File "/home/cm/work/bili_xcode_cluster_api/env/lib/python3.5/site-packages/pymysql/connections.py", line 890, in connect
(self.host, self.port), self.connect_timeout)
File "/usr/lib/python3.5/socket.py", line 711, in create_connection
raise err
File "/usr/lib/python3.5/socket.py", line 702, in create_connection
sock.connect(sa)
BlockingIOError: [Errno 115] Operation now in progress
```
And i found that it all caused by socket.create_connection, socket is setnonblocking if timeout is 0, and then `BlockingIOError: [Errno 115] Operation now in progress` will be raised, so i …

error of socket.create_connection (Python 3.5) if connect_timeout is set to 0

---

.github/ISSUE_TEMPLATE.md

Some issues don't fit template.
In such case, issue report using template just robs my mental energy and time.
This is very critical because I feel I want to throw away this project when seeing such issues.

remove template misused

---

pymysql/connections.py

This enables the reading of some basic SSL parameters from the
configuration file. It gives precedence to the ssl parameters provided
by the class parameter (the ssl dict).

Enable reading SSL parameters from configuration file

---

pymysql/cursors.py

When running bulk insert with executemany(), the regex should allow semicolon at the end of the query.

Allow semicolon at the end of bulk insert query

---

pymysql/connections.py

If _write_bytes fails, _force_close is called which sets self._sock = None. Since we can't call close() on a NoneType, we first check if the attribute is present at all.

Prevent a close() on a NoneType

---

docs/source/conf.py
docs/source/modules/connections.rst
docs/source/modules/cursors.rst
docs/source/modules/index.rst
pymysql/connections.py
pymysql/cursors.py

I added `DictCursor` and `SSDictCursor` to docs and moved the `__init__` docstring for the `Connection` class into the class level docstring, otherwise sphinx won't include the parameter descriptions in the build.
I also added the root path of the directory to the system path in `conf.py`. I was unable to build the docs locally without it and it's necessary for `autodoc` to work.
Related to #571

Update API docs

---

setup.py

TypeError: 'encoding' is an invalid keyword argument for this function

Fix `TypeError` with Python 2.7

---

pymysql/connections.py

For AuthSwitch feature, mysql_native_password and mysql_old_password
should reply only 8-byte or 20-byte scrambled password without '\0'. Use '\0' will let MySQL server reply Error Code 1043 which means Bad HandShake.
Please see the https://web.archive.org/web/20170405005641/https://dev.mysql.com/doc/internals/en/secure-password-authentication.html . 
Also see connections.py line 11130, which also responsed with no '\0'.

Fix connection procedure auth-switch wrong plugin auth method.

---

pymysql/connections.py

MySQL documents annouce the AuthSwitch packet is contains with two
component `auth_plugin_name` and `auth_data`, which `auth_data` is
a string[EOF] string. But in fact it will return a string[NUL] string
or can also say the string[EOF] is consist of a 20bytes string and a '\0'
byte. Now we just follow the document which use those 21bytes as salt
and that is not correct.

Fix handle AuthSwitch packet bug.

---

pymysql/optionfile.py
pymysql/tests/test_optionfile.py

solve current config parser not allow no value
```
ParsingError: File contains parsing errors: /etc/mysql/my.cnf
[line 51]: 'skip-name-resolve\n'
[line 61]: 'skip-external-locking\n'
[line 79]: 'log-bin\n'
[line 125]: 'innodb_file_per_table\n'
````

connection option 'read_default_file'  allow no value

---

pymysql/tests/thirdparty/test_MySQLdb/capabilities.py
pymysql/tests/thirdparty/test_MySQLdb/dbapi20.py
pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_capabilities.py
pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_dbapi20.py

remove shebangs and unusable main code
these python scripts don't contain "main code" (to be executed stand only), I don't see why a shebang (#!) should be added.
the removed "main code" is unusable (as far as I know), when executing it gives the following error: `ImportError: cannot import name 'capabilities'`
The shebang in these scripts are against the packing guidelines for Fedora and requires this patchwork:
http://pkgs.fedoraproject.org/cgit/rpms/python-PyMySQL.git/tree/python-PyMySQL.spec#n64

remove shebangs and unusable main code

---

pymysql/cursors.py
pymysql/tests/test_cursor.py

the [regular expression](../blob/master/pymysql/cursors.py#L15) used to check whether bulk insert/replace is possible is as follows:
```python
RE_INSERT_VALUES = re.compile(
r"\s*((?:INSERT|REPLACE)\s.+\sVALUES?\s+)" +
r"(\(\s*(?:%s|%\(.+\)s)\s*(?:,\s*(?:%s|%\(.+\)s)\s*)*\))" +
r"(\s*(?:ON DUPLICATE.*)?);?\s*\Z",
re.IGNORECASE | re.DOTALL)
```
notice the last `\s+` in the first part of the regular expression requires whitespaces between `VALUES` and left-parenthesis, which means queries like `insert into user values(%s, %s)` would not be considered bulk-insertable. although the demo sql query in the comment of `executemany` has a space between `VALUES` and `(`, i do think this restriction could be relaxed.
This gotcha is so trivial and would cost some time to realize. It actually costed …

allow no whitespaces between `VALUES` and `(` when do bulk insert/replace

---

pymysql/__init__.py

Fix #610 by bumping MySQLdb version to 1.3.12
tested with [django_backend_test](https://github.com/eavictor/django_backend_test), skip BinaryField test (issue 549).
test result (paste here again):
```
EAVICTOR-MBPR:django_backend_test eavictor$ python3 manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.......................................
----------------------------------------------------------------------
Ran 39 tests in 8.070s
OK
Destroying test database for alias 'default'...
EAVICTOR-MBPR:django_backend_test eavictor$ 
```

Bump MySQLdb version from 1.2.6 to 1.3.12

---

CHANGELOG

Improving the grammar and correcting the flag name to `MULTI_STATEMENTS` (with an 's').

CHANGELOG - fix note about MULTI_STATEMENTS

---

pymysql/connections.py
pymysql/cursors.py

I added several links to the PEP 249 documentation. I also documented
the various exceptions that can be raised and, clarified the meaning
of some parameters.
Overall, readers will be able to cross-reference methods with the
specification, and will see implementation-specific info. This will
make it clear that this library implements the full specification,
which is important because there is almost no direct documentation
of this library.
I've confirmed that the docs build correctly using the makefile in `docs/`.
Let me know if I missed anything, or if there are any style issues.

Improve documentation with errors and links

---

pymysql/cursors.py

Rather than making an individual `SET` query for each and every parameter specified for a `callproc` call, use one single call instead, saving round-trip time (if one has more than one parameter). This can be significant if one is making many repeated `callproc` calls which have multiple arguments.
Then only downside I can think of is that if one or more arguments are quite large, combining them all could hit the [max_allowed_packet](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet) limit. However, if it is only e.g. one large argument this will make next to no difference and the user should have an increased `max_allowed_packet` value in anticipation of e.g. larger blobs already.
**Edit**: As far as I can tell the CI test failures are nothing …

Reduce callproc roundtrip time

---

pymysql/tests/test_connection.py

This was discovered testing against MySQL-5.1 because the default engine is MyISAM. The test is explicitly testing transactional operations so force Engine=Innodb.

testfix: MySQL-5.1, test_context requires transactional engine

---

pymysql/cursors.py

A cursor may contain unretrieved results. These should be consumed
before a new cursor is created on the same connection.
Tested on MySQL-5.1
error was:
```
======================================================================
ERROR: test_cleanup_rows_unbuffered (pymysql.tests.test_cursor.CursorTest)
----------------------------------------------------------------------
File "PyMySQL/pymysql/tests/test_cursor.py", line 37, in test_cleanup_rows_unbuffered
c2.execute("select 1")
File "PyMySQL/pymysql/cursors.py", line 172, in execute
result = self._query(query)
File "PyMySQL/pymysql/cursors.py", line 330, in _query
conn.query(q)
File "PyMySQL/pymysql/connections.py", line 890, in query
self._execute_command(COMMAND.COM_QUERY, sql)
File …
```

SSCursor: failed to clear unused results on deletion

---

pymysql/tests/test_issues.py

... like all of the other temporal times.
Without fix fails like:
<pre>
coverage run ./runtests.py pymysql.tests.test_issues.TestOldIssues.test_issue_3
test_issue_3 (pymysql.tests.test_issues.TestOldIssues)
undefined methods datetime_or_None, date_or_None ... FAIL
======================================================================
FAIL: test_issue_3 (pymysql.tests.test_issues.TestOldIssues)
undefined methods datetime_or_None, date_or_None
----------------------------------------------------------------------
File "/home/dan/software_projects/PyMySQL/pymysql/tests/test_issues.py", line 39, in test_issue_3
self.assertTrue(isinstance(c.fetchone()[0], datetime.datetime))
AssertionError: False is not true …

test: issue3 MySQL-8.0 now returns NULL(None) for timestamp

---

.travis.yml
.travis/initializedb.sh

closes #494
By using DB names to include mariadb the Travis output is a lot clear as to what database is being tested:
https://travis-ci.org/grooverdan/PyMySQL/builds/372599838
The MariaDB docker versions are the latest upstream versions and ahead of those provided by Travis. 10.3 is a RC release now so including it.

Travis: use docker for mysql-5.5, mysql-5.6,  mariadb-5.5, 10.0, 10.1, 10.2, 10.3

---

pymysql/tests/test_issues.py
pymysql/tests/thirdparty/test_MySQLdb/capabilities.py

Remove warnings about utf8 usage in MySQL-8.0

Test mysql db capabilities / test_issue_364

---

pymysql/connections.py

Hi methane,
Sorry for disturb you. We are using PyMySQL and have a private proxy code to handle mysql login phase. Recently we faced a connection problem when PyMySQL upgrade to 0.9, and after diagnostic we found that it is a proxy internal bug that assume the auth plugin name should not be empty. We fixed the bug on our hands, but we still want to add the auth plugin name to PyMySQL code like protocol. 
In the MySQL protocol(https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::Handshake ), the client should figure out the auth_plugin_name
```
if capabilities & CLIENT_PLUGIN_AUTH {
string[NUL]    auth plugin name
}
```
We assume when the plugin is mysql_native_password, it should not be empty.
Thanks,
Shuode Li

Add mysql native password plugin name on init handshake phase

---

pymysql/connections.py
pymysql/cursors.py
tox.ini

* Update `tox.ini` to match `.travis.yml` so Python 2.6 isn't listed there
* Use dictionary comprehensions where appropriate, a Python 2.7+ feature. They're a bit faster than creating a list and passing to `dict()`.

Cleanup after Python 2.6 support removed

---

pymysql/connections.py

It is an internal variable and the rendered document can be misread
as if pymysql defaults to server default autocommit mode.

Hide Connection.autocommit_mode docstring

---

pymysql/connections.py

In the socket setup SO_KEEPALIVE (enabling TCP keepalive) is set after the if-branch between local unix and network sockets, setting it for both socket types. This works on Linux, but on Windows Subsystem for Linux, the `sock.setsockopt()` call returns EINVAL, which - while different from Linux - can be argued to make sense since a local unix socket can't really have a TCP keepalive setting.
By moving the SO_KEEPALIVE `sock.setsockopt()` call into the branch for network connections, it works on Wndows as well.

Setting SO_KEEPALIVE only for network connections

---

pymysql/connections.py

Currently, the user gets an unhelpful TypeError for a common and simple mistake. This should help point them in the right direction.

More gracefully handles port coming in as string

---

pymysql/tests/test_basic.py
pymysql/tests/test_issues.py

MySQL 8 deprecates the use of display format for int columns:
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
This results in warnings being generated during test suite
execution which results in test failures.
Drop use of display widths - they don't materially change the tests
so this should be safe across all MySQL versions and variants.

Fix test suite compatibility with MySQL 8

---

pymysql/__init__.py

Recent versions of Django require version 1.3.13 or later of MySQLdb. Otherwise `pymysql.install_as_MySQLdb()` throws an exception:
`django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.`

updated doctored version info for MySQLdb compatibility

---

.travis.yml
.travis/initializedb.sh
README.rst
pymysql/_auth.py
pymysql/connections.py
requirements-dev.txt
setup.py
tests/test_mariadb_auth.py

Initial support for #786 based on PyNaCl. Currently, authentication is
limited to 32bytes-long passwords.

Add ed25519 auth support

---

.travis.yml
pymysql/tests/test_connection.py

unix_socket is inbuilt in MariaDB-10.4+.
MariaDB-10.0 and 10.1 are out of support so replace these with MariaDB supported versions.
Like MySQL-5.5 keep MariaDB-5.5 as an oldest working version.

fix test unix_socket for MariaDB-10.4

---

pymysql/connections.py
pymysql/tests/test_connection.py
requirements-dev.txt

This patch adds a bunch of connection arguments that are compatible with MySQL Connector/Python.
https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html
The rationale for the change is that SQLAlchemy propagates the parameters specified in the DSN's query to the constructor arguments as they are, which means it cannot build a structured parameter to give it to the underlying connection factory. 
MySQL Connector/Python can take unstructued TLS parameters so it plays well with SQLAlchemy.
This patch adds the following arguments:
* `ssl_ca`: Path to the file that contains a PEM-formatted CA certificate
* `ssl_cert`: Path to the file that contains a PEM-formatted client certificate
* `ssl_disabled`: A boolean value that disables usage of TLS
* `ssl_key`: Path to the …

Add MySQL Connector/Python compatible SSL options.

---

setup.py

From your changelog seems like in the latest version you dropped Python 2 support but it is incomplete. You need to set python_requires in your setup.py that will prevent users with Python 2.7 from downloading a sdist version they cannot build.
Note: supporting python_requires requires setuptools>=24.2.0 and pip>=9.0.0 to benefit from it.
Details here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
Here is the current issue if you try to install latest version of fastavro on Python 2:
```
File "<string>", line 1, in <module>
File "c:\users\compile.rdv\appdata\local\temp\pip-install-_ifmxj\PyMySQL\setup.py", line 6, in <module>
with open("./README.rst", encoding="utf-8") as f:
TypeError: 'encoding' is an …
```

Set python_requires='>=3.6'

---

.github/workflows/test.yaml
pymysql/tests/test_connection.py
requirements-dev.txt

Use built-in Python 3 unittest.mock instead of relying on mock package
that is only necessary for ancient versions of Python.

Use built-in unittest.mock

---

pymysql/connections.py

MySQL protocol uses special rules for string longer than 251 characters, listed here: https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
PyMySQL has already been using this for unpacking server messages, but was not used for forming "handshake response" from a client.
We have discovered this on failing of automated tests under Jenkins which are executed at very long paths. By default, PyMySQL fills `program_name` with full path of the running script. The current version generates single byte 0xfe as full length of "client connect attrs".
The proposed patch utilizes already present _lenenc_int() for prefixing formed strings.

Fix generating authentication response with long strings

---

.github/workflows/test.yaml

- concurrency cancels builds in progress e.g. on pull requests
- matrix jobs no longer fail fast, allowing to see failure reasons for all matrix jobs
- coveralls no longer runs on forks, this would fail anyways
see https://github.com/Nothing4You/PyMySQL/actions/runs/1797395406 as example

Improve GitHub workflow

---

.github/workflows/test.yaml
CHANGELOG.md
README.rst
docs/source/user/installation.rst
pymysql/tests/base.py
pymysql/tests/test_basic.py
pymysql/tests/test_connection.py
pymysql/tests/test_issues.py
setup.py

- Python now requires 3.7+, reflected in python_requires
- MySQL now requires 5.7+ in tests
- MariaDB unchanged in tests, only dropped support in documentation
- Added Python 3.11 to test matrix
- Added MariaDB 10.7 to test matrix
- DB version checks have been removed from various tests where no longer needed.
this also results in running a few tests on MariaDB which were previously only
running on MySQL.
Due to the change in `python_requires` I don't think we're necessarily required to bump the version on major/minor level, let me know if you want me to adjust the PR for a different next version.
Fixes #1025

Drop support of EOL Python and DB versions

---

pymysql/connections.py

Explicit support for passing an `ssl.SSLContext` as the `ssl` parameter in `pymysql.connect` was added in https://github.com/PyMySQL/PyMySQL/commit/098a4044ae4f9e922388d13ae7aefde4e7c7d4ba .
This doesn't appear to be documented but I think it could be useful if it were.

Document that the ssl connection parameter can be an SSLContext

---

.github/workflows/codeql-analysis.yml

master branch was renamed to main some time ago, leading to this action no longer working properly, at least for PRs

Fix CodeQL target branch

---

.github/workflows/codeql-analysis.yml

v1 has been deprecated: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Update CodeQL GitHub action to v2

---

pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_dbapi20.py

`test_nextset` has been implemented below. https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_dbapi20.py#L186

tests: remove duplicate test `test_nextset`

---

pymysql/connections.py

Since python 3.3, `socket.error` is a deprecated alias for OSError, which is already included.
https://docs.python.org/3/library/socket.html#socket.error

Remove deprecated socket.error from Connection.connect exception handler

---

pymysql/tests/test_connection.py
pymysql/tests/test_issues.py

There are small typos in:
- pymysql/tests/test_connection.py
- pymysql/tests/test_issues.py
Fixes:
- Should read `password` rather than `passwod`.
- Should read `occurs` rather than `occures`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

setup.cfg

Rather than ignoring all long lines, it is better to set an upper limit on long lines.

flake8: Use max_line_length instead of ignoring E501

---

CHANGELOG.md
pymysql/_auth.py
pymysql/tests/test_DictCursor.py
pymysql/tests/test_basic.py
pymysql/tests/thirdparty/test_MySQLdb/dbapi20.py
pymysql/tests/thirdparty/test_MySQLdb/test_MySQLdb_dbapi20.py

[`codespell --ignore-words-list=decorders,inout --write-changes`](https://pypi.org/project/codespell/)

Fix typos discovered by codespell

---

pyproject.toml

Fix setuptools didn't include pymysql.constants

---

pymysql/connections.py
pymysql/tests/test_connection.py

Send `SET NAMES` on every new connection to ensure charset/collation are correctly configured.
Fix #1092

Add `collation` option and `set_character_set()` to Connection

---

.github/workflows/test.yaml
pyproject.toml

The [Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
See also https://dev.to/hugovk/help-test-python-312-beta-1508/

Add support for Python 3.12

---

pymysql/tests/test_basic.py

MariaDB-11.0.1 removed the 5.5.5 version hack (MDEV-28910).
MariaDB still doesn't support JSON as a type.
Use get_mysql_vendor() == mysql for the final part of test_json.
As tested: https://buildbot.mariadb.org/#/builders/158/builds/7720/steps/4/logs/stdio

test json - mariadb without JSON type

---

pymysql/connections.py

Fixes #1173
---
Addresses the issue of `UnboundLocalError` which occurs when `MySQLResult` class fails to initialize due to a `SystemExit` exception by initialising the `MySQLResult` object before `try/except` block.

Prevent UnboundLocalError on MySQLResult initialization during SystemExit

---

docs/source/user/development.rst

small fix in the docs, the development page still mentions the removed `runtests.py` file.

remove mention of runtests.py

---

.github/workflows/test.yaml
pymysql/connections.py
pyproject.toml

- fixes #1188 
- Add python 3.13 to test matrix and pyproject.toml

Add support for Python 3.13

---

pymysql/charset.py
pymysql/tests/test_charset.py

Current behavior:
```
>>> from pymysql.charset import charset_by_name
>>> print(charset_by_name('UTF8'))
None
>>> print(charset_by_name('utf8'))
Charset(id=45, name='utf8mb4', collation='utf8mb4_general_ci')
>>> print(charset_by_name('latin1'))
Charset(id=8, name='latin1', collation='latin1_swedish_ci')
>>> print(charset_by_name('LATIN1'))
Charset(id=8, name='latin1', collation='latin1_swedish_ci')
```
where I think it's supposed to be able to case-insensitively resolve any `utf8` string into `utf8mb4`

Resolve UTF8 charset case-insensitively
